astra_db:
  collection_name: "ecommercedata"

embedding_model:
  provider: "ollama"
  model_name: "nomic-embed-text:latest"

retriever:
  top_k: 4

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0
    max_output_tokens: 2048

  openai:
     provider: "openai"
     model_name: "gpt-4o"
     temperature: 0

  ollama:
     provider: "ollama"
     model_name: "qwen2.5:0.5b"
     temperature: 0
sqlite:
  SQLITE_Userdb_URL: "sqlite:///./database/chatbox_users.db"
